// file: js/lessons/en-lessons.js (English Lesson Content)
// This file defines the global LESSONS array.

window.LESSONS = [
    // --- SECTION 1: INTRODUCTION & OUTPUT (1-10) ---
    { id: 1, title: "The First Command (println)", prompt: "Print the exact message: <span class='highlight'>Hello, Java World!</span>",
      validation: (input) => input.includes("System.out.println") && input.includes("\"Hello, Java World!\"") && input.includes(";"),
      correct_output: "Hello, Java World!", error_tip: "Ensure your string is in double quotes and ends with a semicolon (;).",
      hint: "The command is 'System.out.println()'.", expected_code: "System.out.println(\"Hello, Java World!\");" },
    { id: 2, title: "Printing Numbers", prompt: "Print the number 19164 directly (without quotes).",
      validation: (input) => input.includes("System.out.println") && input.includes("19164") && !input.includes("\"19164\"") && input.includes(";"),
      correct_output: "19164", error_tip: "Numbers do not require double quotes.",
      hint: "Just put the number inside the parentheses.", expected_code: "System.out.println(19164);" },
    { id: 3, title: "Printing without Newline (print)", prompt: "Use `System.out.print` to display <span class='highlight'>A</span>, then <span class='highlight'>B</span> on the SAME line.",
      validation: (input) => input.includes("System.out.print(\"A\")") && input.includes("System.out.print(\"B\")"),
      correct_output: "AB", error_tip: "Use 'System.out.print()' for both messages.",
      hint: "Use 'System.out.print(\"A\"); System.out.print(\"B\");'", expected_code: "System.out.print(\"A\");\nSystem.out.print(\"B\");" },
    { id: 4, title: "Adding Comments (Single Line)", prompt: "Write a single-line comment that says: <span class='highlight'>Mission Critical Code</span>.",
      validation: (input) => input.includes("//Mission Critical Code"), correct_output: "(Success! No output expected)",
      error_tip: "Single-line comments start with a double slash (//).",
      hint: "Type '//' followed by the message.", expected_code: "// Mission Critical Code" },
    { id: 5, title: "Block Comments", prompt: "Write a block comment spanning one line that says: <span class='highlight'>Important!</span>",
      validation: (input) => input.includes("/*Important!*/") || input.includes("/* Important! */"),
      correct_output: "(Success! No output expected)", error_tip: "Block comments use /* ... */",
      hint: "Use /* at the start and */ at the end.", expected_code: "/* Important! */" },
    { id: 6, title: "Printing Calculations", prompt: "Print the result of 15 * 3 (15 multiplied by 3).",
      validation: (input) => input.includes("System.out.println") && input.includes("15 * 3") && input.includes(";"),
      correct_output: "45", error_tip: "Use the asterisk (*) for multiplication.",
      hint: "Place the full math expression inside println().", expected_code: "System.out.println(15 * 3);" },
    { id: 7, title: "Escape Sequences (Newline)", prompt: "Print the message: <span class='highlight'>Line 1</span> followed by a newline, then <span class='highlight'>Line 2</span>, using only one println command.",
      validation: (input) => input.includes("\"Line 1\\nLine 2\""),
      correct_output: "Line 1\nLine 2", error_tip: "The newline escape sequence is \\n.",
      hint: "The string should be \"Line 1\\nLine 2\".", expected_code: "System.out.println(\"Line 1\\nLine 2\");" },
    { id: 8, title: "Printing Multiple Lines", prompt: "Print 'Oreo' on the first line and 'Studios' on the second line using two separate println statements.",
      validation: (input) => input.includes("println(\"Oreo\")") && input.includes("println(\"Studios\")"),
      correct_output: "Oreo\nStudios", error_tip: "Each line needs its own System.out.println().",
      hint: "Use System.out.println() twice.", expected_code: "System.out.println(\"Oreo\");\nSystem.out.println(\"Studios\");" },
    { id: 9, title: "Tab Escape", prompt: "Print the word 'Java' followed by a tab, then 'Engineer'.",
      validation: (input) => input.includes("\"Java\\tEngineer\""),
      correct_output: "Java\tEngineer", error_tip: "The tab escape sequence is \\t.",
      hint: "The tab escape sequence is backslash t.", expected_code: "System.out.println(\"Java\\tEngineer\");" },
    { id: 10, title: "Quoting Escape", prompt: "Print the message: <span class='highlight'>He said, \"Run!\"</span> using the correct escape sequence.",
      validation: (input) => input.includes("\"He said, \\\"Run!\\\"\""),
      correct_output: "He said, \"Run!\"", error_tip: "Use \\\" to print double quotes.",
      hint: "Use a backslash before each quote you want to print.", expected_code: "System.out.println(\"He said, \\\"Run!\\\"\");" },

    // --- SECTION 2: VARIABLES & BASIC DATA TYPES (11-20) ---
    { id: 11, title: "Declaring and Printing Int", prompt: "Declare an integer `count` and assign it the value 15. Print `count`.",
      validation: (input) => input.includes("int count") && input.includes("15") && input.includes("println(count)"),
      correct_output: "15", error_tip: "Use the 'int' keyword for the variable.",
      hint: "Start with: `int count = 15;`", expected_code: "int count = 15;\nSystem.out.println(count);" },
    { id: 12, title: "Declaring Double", prompt: "Declare a double `pi` and assign it the value 3.14. Print `pi`.",
      validation: (input) => input.includes("double pi") && input.includes("3.14") && input.includes("println(pi)"),
      correct_output: "3.14", error_tip: "Floating-point numbers use the 'double' type.",
      hint: "The type keyword is 'double'.", expected_code: "double pi = 3.14;\nSystem.out.println(pi);" },
    { id: 13, title: "Declaring Boolean", prompt: "Declare a boolean `isReady` and set it to `false`. Print `isReady`.",
      validation: (input) => input.includes("boolean isReady") && input.includes("false") && input.includes("println(isReady)"),
      correct_output: "false", error_tip: "Boolean values are 'true' or 'false' (lowercase).",
      hint: "The type keyword is 'boolean'.", expected_code: "boolean isReady = false;\nSystem.out.println(isReady);" },
    { id: 14, title: "Declaring Char", prompt: "Declare a char `initial` and set it to 'E'. Print `initial`.",
      validation: (input) => input.includes("char initial") && input.includes("'E'") && input.includes("println(initial)"),
      correct_output: "E", error_tip: "Char values use single quotes (').",
      hint: "Remember to use single quotes for char values.", expected_code: "char initial = 'E';\nSystem.out.println(initial);" },
    { id: 15, title: "Declaring String", prompt: "Declare a String `city` and set it to \"Strasbourg\". Print `city`.",
      validation: (input) => input.includes("String city") && input.includes("\"Strasbourg\"") && input.includes("println(city)"),
      correct_output: "Strasbourg", error_tip: "String starts with a capital 'S' and uses double quotes.",
      hint: "The type keyword is 'String'.", expected_code: "String city = \"Strasbourg\";\nSystem.out.println(city);" },
    { id: 16, title: "Reassigning Variables", prompt: "Start with `int x = 5;`. Reassign `x` to 10 on the next line. Print `x`.",
      validation: (input) => input.includes("int x = 5") && input.includes("x = 10") && input.includes("println(x)"),
      correct_output: "10", error_tip: "You only need the variable name (x = 10) for reassignment.",
      hint: "Don't use 'int' when reassigning.", expected_code: "int x = 5;\nx = 10;\nSystem.out.println(x);" },
    { id: 17, title: "Combining Output", prompt: "Given `String item = \"Monitor\";` and `double price = 299.99;`. Print both: \"Monitor costs 299.99\".",
      validation: (input) => input.includes("String item") && input.includes("double price") && input.includes("\" costs \"") && input.includes("item + \" costs \" + price"),
      correct_output: "Monitor costs 299.99", error_tip: "Use the '+' operator to concatenate Strings and variables.",
      hint: "Use: `System.out.println(item + \" costs \" + price);`", expected_code: "String item = \"Monitor\";\ndouble price = 299.99;\nSystem.out.println(item + \" costs \" + price);" },
    { id: 18, title: "Constants (final)", prompt: "Declare an integer constant named `MAX_SIZE` with a value of 256. Print the constant.",
      validation: (input) => input.includes("final int MAX_SIZE") && input.includes("256") && input.includes("println(MAX_SIZE)"),
      correct_output: "256", error_tip: "Constants use the 'final' keyword and are typically named in ALL CAPS.",
      hint: "Start with: `final int MAX_SIZE = 256;`", expected_code: "final int MAX_SIZE = 256;\nSystem.out.println(MAX_SIZE);" },
    { id: 19, title: "Var Keyword", prompt: "Use the `var` keyword to declare a variable `version` initialized to the string \"1.21\". Print it.",
      validation: (input) => input.includes("var version") && input.includes("\"1.21\"") && input.includes("println(version)"),
      correct_output: "1.21", error_tip: "Use 'var' instead of an explicit type (like String) for local variable type inference.",
      hint: "Use: `var version = \"1.21\";`", expected_code: "var version = \"1.21\";\nSystem.out.println(version);" },
    { id: 20, title: "String Length", prompt: "Given `String word = \"RabbitMQ\";`. Use a String method to print the length of the word.",
      validation: (input) => input.includes("String word") && input.includes("word.length()") && input.includes("println"),
      correct_output: "8", error_tip: "The method to get the length is `.length()` (with parentheses).",
      hint: "Use the `.length()` method.", expected_code: "String word = \"RabbitMQ\";\nSystem.out.println(word.length());" },

    // --- SECTION 3: ARITHMETIC & OPERATORS (21-35) ---
    { id: 21, title: "Addition Operator (+)", prompt: "Calculate the sum of 100 + 40. Store it in an integer `sum` and print `sum`.",
      validation: (input) => input.includes("int sum") && input.includes("100 + 40") && input.includes("println(sum)"),
      correct_output: "140", error_tip: "Use the '+' operator.",
      hint: "The structure is: `int sum = 100 + 40;`", expected_code: "int sum = 100 + 40;\nSystem.out.println(sum);" },
    { id: 22, title: "Subtraction Operator (-)", prompt: "Calculate 95 minus 23. Store it in an integer `difference` and print.",
      validation: (input) => input.includes("int difference") && input.includes("95 - 23") && input.includes("println(difference)"),
      correct_output: "72", error_tip: "Use the '-' operator.",
      hint: "The calculation is 95 - 23.", expected_code: "int difference = 95 - 23;\nSystem.out.println(difference);" },
    { id: 23, title: "Division Operator (/) (Int)", prompt: "Calculate 10 divided by 3. Store the result in `result` (int) and print.",
      validation: (input) => input.includes("int result") && input.includes("10 / 3") && input.includes("println(result)"),
      correct_output: "3", error_tip: "Integer division truncates the decimal part.",
      hint: "Use the '/' operator.", expected_code: "int result = 10 / 3;\nSystem.out.println(result);" },
    { id: 24, title: "Division Operator (/) (Double)", prompt: "Calculate 10.0 divided by 3.0. Store the result in `result` (double) and print.",
      validation: (input) => input.includes("double result") && input.includes("10.0 / 3.0") && input.includes("println(result)"),
      correct_output: "3.3333333333333335", error_tip: "Use floating-point numbers (10.0, 3.0) for accurate division.",
      hint: "Use the '/' operator with doubles.", expected_code: "double result = 10.0 / 3.0;\nSystem.out.println(result);" },
    { id: 25, title: "Multiplication Operator (*)", prompt: "Calculate 12 * 7. Store it in an integer `product` and print.",
      validation: (input) => input.includes("int product") && input.includes("12 * 7") && input.includes("println(product)"),
      correct_output: "84", error_tip: "Use the '*' operator.",
      hint: "The calculation is 12 * 7.", expected_code: "int product = 12 * 7;\nSystem.out.println(product);" },
    { id: 26, title: "The Modulus Operator (%)", prompt: "Calculate the remainder of 20 divided by 7. Store it in `remainder` (int) and print.",
      validation: (input) => input.includes("int remainder") && input.includes("20 % 7") && input.includes("println(remainder)"),
      correct_output: "6", error_tip: "The modulus operator is the percent sign (%).",
      hint: "The calculation is: 20 % 7;", expected_code: "int remainder = 20 % 7;\nSystem.out.println(remainder);" },
    { id: 27, title: "Pre-Increment Operator (++x)", prompt: "Start with `int x = 5;`. Use the pre-increment operator on `x`. Print `x`.",
      validation: (input) => input.includes("int x = 5") && input.includes("++x") && input.includes("println(x)"),
      correct_output: "6", error_tip: "The pre-increment operator is ++ before the variable.",
      hint: "Use `++x;` before the print statement.", expected_code: "int x = 5;\n++x;\nSystem.out.println(x);" },
    { id: 28, title: "Post-Decrement Operator (x--)", prompt: "Start with `int y = 8;`. Use the post-decrement operator on `y`. Print `y`.",
      validation: (input) => input.includes("int y = 8") && input.includes("y--") && input.includes("println(y)"),
      correct_output: "7", error_tip: "The post-decrement operator is -- after the variable.",
      hint: "Use `y--;` after declaration.", expected_code: "int y = 8;\ny--;\nSystem.out.println(y);" },
    { id: 29, title: "Compound Addition (+=)", prompt: "Start with `int gold = 10;`. Add 15 to `gold` using compound assignment. Print `gold`.",
      validation: (input) => input.includes("int gold = 10") && input.includes("gold += 15") && input.includes("println(gold)"),
      correct_output: "25", error_tip: "Compound addition is the `+=` operator.",
      hint: "Use: `gold += 15;`", expected_code: "int gold = 10;\ngold += 15;\nSystem.out.println(gold);" },
    { id: 30, title: "Compound Subtraction (-=)", prompt: "Start with `int shield = 100;`. Subtract 25 from `shield` using compound assignment. Print `shield`.",
      validation: (input) => input.includes("int shield = 100") && input.includes("shield -= 25") && input.includes("println(shield)"),
      correct_output: "75", error_tip: "Compound subtraction is the `-=` operator.",
      hint: "Use: `shield -= 25;`", expected_code: "int shield = 100;\nshield -= 25;\nSystem.out.println(shield);" },
    { id: 31, title: "Compound Multiplication (*=)", prompt: "Start with `int multiplier = 5;`. Multiply `multiplier` by 4 using compound assignment. Print `multiplier`.",
      validation: (input) => input.includes("int multiplier = 5") && input.includes("multiplier *= 4") && input.includes("println(multiplier)"),
      correct_output: "20", error_tip: "Compound multiplication is the `*=` operator.",
      hint: "Use: `multiplier *= 4;`", expected_code: "int multiplier = 5;\nmultiplier *= 4;\nSystem.out.println(multiplier);" },
    { id: 32, title: "Compound Division (/=)", prompt: "Start with `int total = 40;`. Divide `total` by 8 using compound assignment. Print `total`.",
      validation: (input) => input.includes("int total = 40") && input.includes("total /= 8") && input.includes("println(total)"),
      correct_output: "5", error_tip: "Compound division is the `/=` operator.",
      hint: "Use: `total /= 8;`", expected_code: "int total = 40;\ntotal /= 8;\nSystem.out.println(total);" },
    { id: 33, title: "Order of Operations", prompt: "Calculate the result of 2 + 3 * 4. Store it in `result` (int) and print.",
      validation: (input) => input.includes("int result") && input.includes("2 + 3 * 4") && input.includes("println(result)"),
      correct_output: "14", error_tip: "Multiplication happens before addition (PEMDAS/BODMAS).",
      hint: "The calculation evaluates to 2 + 12.", expected_code: "int result = 2 + 3 * 4;\nSystem.out.println(result);" },
    { id: 34, title: "Parentheses in Math", prompt: "Calculate the result of (2 + 3) * 4. Store it in `result` (int) and print.",
      validation: (input) => input.includes("int result") && input.includes("(2 + 3) * 4") && input.includes("println(result)"),
      correct_output: "20", error_tip: "Parentheses force the inner operation to happen first.",
      hint: "The calculation evaluates to 5 * 4.", expected_code: "int result = (2 + 3) * 4;\nSystem.out.println(result);" },
    { id: 35, title: "Type Conversion (Int to Double)", prompt: "Given `int integerVal = 5;`. Explicitly cast it to a double, store it in `doubleVal`, and print `doubleVal`.",
      validation: (input) => input.includes("int integerVal = 5") && input.includes("double doubleVal") && input.includes("doubleVal = (double)integerVal") && input.includes("println(doubleVal)"),
      correct_output: "5.0", error_tip: "Use casting syntax: `(double)variableName`.",
      hint: "The casting syntax is `(double) integerVal`.", expected_code: "int integerVal = 5;\ndouble doubleVal = (double)integerVal;\nSystem.out.println(doubleVal);" },
    
    // --- SECTION 4: CONDITIONAL LOGIC (36-50) ---
    { id: 36, title: "Simple `if` Statement", prompt: "Given `int temp = 25;`. If `temp` is greater than 20, print <span class='highlight'>Hot day!</span>",
      validation: (input) => input.includes("int temp = 25") && input.includes("if (temp > 20)") && input.includes("\"Hot day!\""),
      correct_output: "Hot day!", error_tip: "Use the `>` comparison operator and the `if (condition)` structure.",
      hint: "You need `int temp = 25;` and then `if (temp > 20) { ... }`", expected_code: "int temp = 25;\nif (temp > 20) {\nSystem.out.println(\"Hot day!\");\n}" },
    { id: 37, title: "The `if-else` Block", prompt: "Given `int speed = 50;`. If `speed` is greater than 60, print <span class='highlight'>Too fast</span>, otherwise print <span class='highlight'>OK speed</span>.",
      validation: (input) => input.includes("int speed = 50") && input.includes("if (speed > 60)") && input.includes("else") && input.includes("\"Too fast\"") && input.includes("\"OK speed\""),
      correct_output: "OK speed", error_tip: "Remember the `else` block executes when the `if` condition is false.",
      hint: "The output should come from the `else` block.", expected_code: "int speed = 50;\nif (speed > 60) {\nSystem.out.println(\"Too fast\");\n} else {\nSystem.out.println(\"OK speed\");\n}" },
    { id: 38, title: "Equality Operator (==)", prompt: "Given `int a = 7; int b = 7;`. If `a` is equal to `b`, print <span class='highlight'>Match</span>.",
      validation: (input) => input.includes("int a = 7") && input.includes("int b = 7") && input.includes("if (a == b)") && input.includes("\"Match\""),
      correct_output: "Match", error_tip: "Equality uses the double equals sign (`==`).",
      hint: "The condition is `if (a == b)`.", expected_code: "int a = 7;\nint b = 7;\nif (a == b) {\nSystem.out.println(\"Match\");\n}" },
    { id: 39, title: "Inequality Operator (!=)", prompt: "Given `int x = 5; int y = 6;`. If `x` is NOT equal to `y`, print <span class='highlight'>Different</span>.",
      validation: (input) => input.includes("int x = 5") && input.includes("int y = 6") && input.includes("if (x != y)") && input.includes("\"Different\""),
      correct_output: "Different", error_tip: "Inequality uses `!=`.",
      hint: "The condition is `if (x != y)`.", expected_code: "int x = 5;\nint y = 6;\nif (x != y) {\nSystem.out.println(\"Different\");\n}" },
    { id: 40, title: "Greater Than or Equal To (>=)", prompt: "Given `int level = 15;`. If `level` is greater than or equal to 10, print <span class='highlight'>High enough</span>.",
      validation: (input) => input.includes("int level = 15") && input.includes("if (level >= 10)") && input.includes("\"High enough\""),
      correct_output: "High enough", error_tip: "Use the `>=` operator.",
      hint: "The condition is `if (level >= 10)`.", expected_code: "int level = 15;\nif (level >= 10) {\nSystem.out.println(\"High enough\");\n}" },
    { id: 41, title: "Less Than or Equal To (<=)", prompt: "Given `int health = 40;`. If `health` is less than or equal to 50, print <span class='highlight'>Not Critical</span>.",
      validation: (input) => input.includes("int health = 40") && input.includes("if (health <= 50)") && input.includes("\"Not Critical\""),
      correct_output: "Not Critical", error_tip: "Use the `<=` operator.",
      hint: "The condition is `if (health <= 50)`.", expected_code: "int health = 40;\nif (health <= 50) {\nSystem.out.println(\"Not Critical\");\n}" },
    { id: 42, title: "Logical AND (`&&`)", prompt: "Given `int age = 20; boolean isStudent = true;`. If `age` is > 18 AND `isStudent` is true, print <span class='highlight'>Eligible</span>.",
      validation: (input) => input.includes("int age = 20") && input.includes("boolean isStudent = true") && input.includes("if (age > 18 && isStudent)") && input.includes("\"Eligible\""),
      correct_output: "Eligible", error_tip: "The Logical AND operator is `&&`.",
      hint: "The condition is `if (age > 18 && isStudent)`.", expected_code: "int age = 20;\nboolean isStudent = true;\nif (age > 18 && isStudent) {\nSystem.out.println(\"Eligible\");\n}" },
    { id: 43, title: "Logical OR (`||`)", prompt: "Given `int score = 80; boolean perfectAttendance = false;`. If `score` is > 90 OR `perfectAttendance` is true, print <span class='highlight'>Bonus!</span> (No bonus expected).",
      validation: (input) => input.includes("int score = 80") && input.includes("boolean perfectAttendance = false") && input.includes("if (score > 90 || perfectAttendance)") && input.includes("Bonus!") && input.includes("else"),
      correct_output: "", error_tip: "The Logical OR operator is `||`. Since the condition is false, no output should be generated without an else block.",
      hint: "The condition is `if (score > 90 || perfectAttendance) { ... }`", expected_code: "int score = 80;\nboolean perfectAttendance = false;\nif (score > 90 || perfectAttendance) {\nSystem.out.println(\"Bonus!\");\n}" },
    { id: 44, title: "Logical NOT (`!`)", prompt: "Given `boolean hasPower = false;`. If `hasPower` is NOT true, print <span class='highlight'>Generator offline</span>.",
      validation: (input) => input.includes("boolean hasPower = false") && input.includes("if (!hasPower)") && input.includes("\"Generator offline\""),
      correct_output: "Generator offline", error_tip: "The Logical NOT operator is `!` before the boolean variable/expression.",
      hint: "The condition is `if (!hasPower)`.", expected_code: "boolean hasPower = false;\nif (!hasPower) {\nSystem.out.println(\"Generator offline\");\n}" },
    { id: 45, title: "`if-else if-else` Chain", prompt: "Given `int day = 3;`. If day is 1, print 'Mon'; if day is 2, print 'Tue'; otherwise print 'Other day'.",
      validation: (input) => input.includes("int day = 3") && input.includes("if (day == 1)") && input.includes("else if (day == 2)") && input.includes("else") && input.includes("\"Other day\""),
      correct_output: "Other day", error_tip: "Use `else if` for the intermediate condition.",
      hint: "Start with: `if (day == 1) { ... } else if (day == 2) { ... } else { ... }`", expected_code: "int day = 3;\nif (day == 1) {\nSystem.out.println(\"Mon\");\n} else if (day == 2) {\nSystem.out.println(\"Tue\");\n} else {\nSystem.out.println(\"Other day\");\n}" },
    { id: 46, title: "String Comparison (equals)", prompt: "Given `String city = \"Paris\";`. If `city` equals \"Paris\", print <span class='highlight'>Eiffel Tower</span>.",
      validation: (input) => input.includes("String city = \"Paris\"") && input.includes("city.equals(\"Paris\")") && input.includes("println"),
      correct_output: "Eiffel Tower", error_tip: "To compare Strings for equality, use the `.equals()` method, not `==`.",
      hint: "The condition is: `if (city.equals(\"Paris\"))`", expected_code: "String city = \"Paris\";\nif (city.equals(\"Paris\")) {\nSystem.out.println(\"Eiffel Tower\");\n}" },
    { id: 47, title: "String Comparison (equalsIgnoreCase)", prompt: "Given `String code = \"EXIT\";`. If `code` equals \"exit\" (ignoring case), print <span class='highlight'>Shutdown</span>.",
      validation: (input) => input.includes("String code = \"EXIT\"") && input.includes("code.equalsIgnoreCase(\"exit\")") && input.includes("println"),
      correct_output: "Shutdown", error_tip: "Use the `.equalsIgnoreCase()` method.",
      hint: "The condition is: `if (code.equalsIgnoreCase(\"exit\"))`", expected_code: "String code = \"EXIT\";\nif (code.equalsIgnoreCase(\"exit\")) {\nSystem.out.println(\"Shutdown\");\n}" },
    { id: 48, title: "Ternary Operator (1)", prompt: "Given `int fuel = 10;`. Use the ternary operator to print \"Low\" if `fuel` < 20, otherwise print \"OK\".",
      validation: (input) => input.includes("int fuel = 10") && input.includes("fuel < 20 ? \"Low\" : \"OK\"") && input.includes("println"),
      correct_output: "Low", error_tip: "The syntax is `condition ? valueIfTrue : valueIfFalse`.",
      hint: "Use `(fuel < 20 ? \"Low\" : \"OK\")` inside println().", expected_code: "int fuel = 10;\nSystem.out.println(fuel < 20 ? \"Low\" : \"OK\");" },
    { id: 49, title: "Ternary Operator (2)", prompt: "Given `boolean isNight = true;`. Use the ternary operator to print the variable `status` as \"Sleep\" if true, or \"Work\" if false.",
      validation: (input) => input.includes("boolean isNight = true") && input.includes("String status") && input.includes("isNight ? \"Sleep\" : \"Work\"") && input.includes("println(status)"),
      correct_output: "Sleep", error_tip: "Assign the result of the ternary operation to the String variable `status`.",
      hint: "The assignment should be: `String status = isNight ? \"Sleep\" : \"Work\";`", expected_code: "boolean isNight = true;\nString status = isNight ? \"Sleep\" : \"Work\";\nSystem.out.println(status);" },
    { id: 50, title: "The `switch` Statement (int)", prompt: "Given `int color = 2;`. Use a switch statement to print \"Red\" if color is 1, or \"Blue\" if color is 2. (Use default for safety, but don't print anything there).",
      validation: (input) => input.includes("int color = 2") && input.includes("switch (color)") && input.includes("case 2:") && input.includes("\"Blue\"") && input.includes("break") && input.includes("default:"),
      correct_output: "Blue", error_tip: "Remember to use `break;` after each case and include a `default` case.",
      hint: "The switch expression goes in parentheses: `switch (color)`.", expected_code: "int color = 2;\nswitch (color) {\ncase 1: System.out.println(\"Red\"); break;\ncase 2: System.out.println(\"Blue\"); break;\ndefault: break;\n}" },

    // --- SECTION 5: LOOPS (51-65) ---
    { id: 51, title: "Basic `for` Loop", prompt: "Write a `for` loop that iterates 5 times (i=0 to i<5). Print the message <span class='highlight'>Loop!</span> inside the loop.",
      validation: (input) => input.includes("for (int i = 0; i < 5; i++)") && input.includes("\"Loop!\""),
      correct_output: "Loop!\nLoop!\nLoop!\nLoop!\nLoop!", error_tip: "Ensure your initialization, condition, and increment are correct: `i = 0; i < 5; i++`.",
      hint: "The structure is: `for (int i = 0; i < 5; i++) { ... }`", expected_code: "for (int i = 0; i < 5; i++) {\nSystem.out.println(\"Loop!\");\n}" },
    { id: 52, title: "Printing Loop Index", prompt: "Write a `for` loop that prints the index `i` from 1 up to and including 3.",
      validation: (input) => input.includes("for (int i = 1; i <= 3; i++)") && input.includes("println(i)"),
      correct_output: "1\n2\n3", error_tip: "Use `i <= 3` to include 3, and initialize `i` to 1.",
      hint: "Initialize i to 1 and use the condition `i <= 3`.", expected_code: "for (int i = 1; i <= 3; i++) {\nSystem.out.println(i);\n}" },
    { id: 53, title: "`for` Loop Decrementing", prompt: "Write a `for` loop that prints numbers backward from 5 down to 1.",
      validation: (input) => input.includes("for (int i = 5; i >= 1; i--") && input.includes("println(i)"),
      correct_output: "5\n4\n3\n2\n1", error_tip: "Use `i--` for decrementing and `i >= 1` for the condition.",
      hint: "The loop header should be: `for (int i = 5; i >= 1; i--)`.", expected_code: "for (int i = 5; i >= 1; i--) {\nSystem.out.println(i);\n}" },
    { id: 54, title: "Basic `while` Loop", prompt: "Use a `while` loop to print <span class='highlight'>Run</span> 3 times. Use `int count = 0;` and increment it.",
      validation: (input) => input.includes("int count = 0") && input.includes("while (count < 3)") && input.includes("\"Run\"") && input.includes("count++"),
      correct_output: "Run\nRun\nRun", error_tip: "Remember to increment the counter inside the loop to avoid an infinite loop.",
      hint: "Initialize count outside, then `while (count < 3) { ... count++; }`", expected_code: "int count = 0;\nwhile (count < 3) {\nSystem.out.println(\"Run\");\ncount++;\n}" },
    { id: 55, title: "Basic `do-while` Loop", prompt: "Use a `do-while` loop to print the number 1 once. Use `int x = 1;` and the condition `x < 1`.",
      validation: (input) => input.includes("int x = 1") && input.includes("do {") && input.includes("println(x)") && input.includes("} while (x < 1)"),
      correct_output: "1", error_tip: "The `do-while` loop executes at least once, even if the condition is initially false.",
      hint: "Initialize `x` to 1. The loop prints 1, then checks `while (x < 1)`.", expected_code: "int x = 1;\ndo {\nSystem.out.println(x);\n} while (x < 1);" },
    { id: 56, title: "`break` in `for` Loop", prompt: "Write a `for` loop from 1 to 10. Print the number, but use `break` to stop the loop when the number equals 4.",
      validation: (input) => input.includes("for (int i = 1; i <= 10; i++)") && input.includes("if (i == 4)") && input.includes("break;"),
      correct_output: "1\n2\n3", error_tip: "The `break` statement immediately exits the loop.",
      hint: "Inside the loop, use `if (i == 4) { break; }` before printing i.", expected_code: "for (int i = 1; i <= 10; i++) {\nif (i == 4) {\nbreak;\n}\nSystem.out.println(i);\n}" },
    { id: 57, title: "`continue` in `for` Loop", prompt: "Write a `for` loop from 1 to 5. Use `continue` to skip printing the number 3.",
      validation: (input) => input.includes("for (int i = 1; i <= 5; i++)") && input.includes("if (i == 3)") && input.includes("continue;"),
      correct_output: "1\n2\n4\n5", error_tip: "The `continue` statement skips the rest of the current iteration.",
      hint: "Use `if (i == 3) { continue; }` before the print statement.", expected_code: "for (int i = 1; i <= 5; i++) {\nif (i == 3) {\ncontinue;\n}\nSystem.out.println(i);\n}" },
    { id: 58, title: "Nested `for` Loops (1)", prompt: "Use nested `for` loops to print <span class='highlight'>X</span> in a 2x2 square (4 times total).",
      validation: (input) => input.includes("for (int i = 0; i < 2; i++)") && input.includes("for (int j = 0; j < 2; j++)") && input.includes("println(\"X\")"),
      correct_output: "X\nX\nX\nX", error_tip: "You need one loop inside another loop, both iterating twice.",
      hint: "Both loops should iterate from 0 to 2 (exclusive).", expected_code: "for (int i = 0; i < 2; i++) {\nfor (int j = 0; j < 2; j++) {\nSystem.out.println(\"X\");\n}\n}" },
    { id: 59, title: "Nested `for` Loops (2)", prompt: "Print a multiplication table header: <span class='highlight'>1 2</span>, then a newline, then <span class='highlight'>2 4</span> (Use only one outer loop for i=1 to 2, and an inner loop for j=1 to 2). Use `print` for the numbers and `println` for the newline.",
      validation: (input) => input.includes("for (int i = 1; i <= 2; i++)") && input.includes("for (int j = 1; j <= 2; j++)") && input.includes("print(i * j + \" \")") && input.includes("println()"),
      correct_output: "1 2 \n2 4 ", error_tip: "Use `print` to keep numbers on the same line and an empty `println()` to move to the next line.",
      hint: "Use `System.out.print(i * j + \" \");` inside the inner loop, and `System.out.println();` after the inner loop finishes.", expected_code: "for (int i = 1; i <= 2; i++) {\nfor (int j = 1; j <= 2; j++) {\nSystem.out.print(i * j + \" \");\n}\nSystem.out.println();\n}" },
    { id: 60, title: "Enhanced `for` Loop (Array Iteration)", prompt: "Given `String[] items = {\"Sword\", \"Shield\", \"Helmet\"};`. Use an enhanced `for` loop to print each item.",
      validation: (input) => input.includes("String[] items = {\"Sword\", \"Shield\", \"Helmet\"}") && input.includes("for (String item : items)") && input.includes("println(item)"),
      correct_output: "Sword\nShield\nHelmet", error_tip: "The enhanced loop syntax is: `for (Type element : array) { ... }`",
      hint: "The loop header is `for (String item : items)`.", expected_code: "String[] items = {\"Sword\", \"Cat\", \"Bird\"};\nfor (String item : items) {\nSystem.out.println(item);\n}" },
    { id: 61, title: "`while` Loop with Sentinel", prompt: "Given `int pin = 1234; int attempt = 1234;`. Use a `while` loop that continues *as long as* `pin` is not equal to `attempt`. Inside the loop, print <span class='highlight'>Mismatch</span>.",
      validation: (input) => input.includes("int pin = 1234") && input.includes("int attempt = 1234") && input.includes("while (pin != attempt)") && input.includes("\"Mismatch\""),
      correct_output: "", error_tip: "Since pin equals attempt, the loop condition must be false initially, resulting in no output.",
      hint: "The condition is `while (pin != attempt)`.", expected_code: "int pin = 1234;\nint attempt = 1234;\nwhile (pin != attempt) {\nSystem.out.println(\"Mismatch\");\n}" },
    { id: 62, title: "Calculating Sum in a Loop", prompt: "Use a `for` loop to calculate the sum of numbers from 1 to 5. Print the final `sum` (which should be 15).",
      validation: (input) => input.includes("int sum = 0") && input.includes("for (int i = 1; i <= 5; i++)") && input.includes("sum = sum + i") && input.includes("println(sum)"),
      correct_output: "15", error_tip: "You need an outer variable `sum` initialized to 0, and `sum = sum + i;` inside the loop.",
      hint: "The final `println(sum)` must be outside the loop.", expected_code: "int sum = 0;\nfor (int i = 1; i <= 5; i++) {\nsum = sum + i;\n}\nSystem.out.println(sum);" },
    { id: 63, title: "Looping Over Array Length", prompt: "Given `int[] data = {10, 20, 30};`. Use a standard `for` loop to print each element by looping up to the array's length.",
      validation: (input) => input.includes("int[] data") && input.includes("for (int i = 0; i < data.length; i++)") && input.includes("println(data[i])"),
      correct_output: "10\n20\n30", error_tip: "Access the length using `.length` (no parentheses).",
      hint: "The loop condition is `i < data.length`.", expected_code: "int[] data = {10, 20, 30};\nfor (int i = 0; i < data.length; i++) {\nSystem.out.println(data[i]);\n}" },
    { id: 64, title: "`do-while` Loop with Increment", prompt: "Use a `do-while` loop to print numbers starting from 2 up to, but not including, 5. Use `int i = 2;` and increment it inside the loop.",
      validation: (input) => input.includes("int i = 2") && input.includes("do {") && input.includes("println(i)") && input.includes("i++") && input.includes("} while (i < 5)"),
      correct_output: "2\n3\n4", error_tip: "The condition should be `i < 5` to stop before 5.",
      hint: "The loop must execute its body before checking the condition.", expected_code: "int i = 2;\ndo {\nSystem.out.println(i);\ni++;\n} while (i < 5);" },
    { id: 65, title: "Skipping Multiples (Continue)", prompt: "Use a `for` loop from 1 to 6. Use `continue` to skip printing numbers that are evenly divisible by 2 (2, 4, 6).",
      validation: (input) => input.includes("for (int i = 1; i <= 6; i++)") && input.includes("if (i % 2 == 0)") && input.includes("continue;") && input.includes("println(i)"),
      correct_output: "1\n3\n5", error_tip: "Use the modulus operator (`%`) to check divisibility. If `i % 2 == 0`, use `continue`.",
      hint: "Use `i % 2 == 0` as the condition for the `if` statement.", expected_code: "for (int i = 1; i <= 6; i++) {\nif (i % 2 == 0) {\ncontinue;\n}\nSystem.out.println(i);\n}" },

    // --- SECTION 6: ARRAYS (66-75) ---
    { id: 66, title: "Array Initialization (Size)", prompt: "Initialize an integer array named `data` to hold 4 elements. Print the first element (which will be 0).",
      validation: (input) => input.includes("int[] data = new int[4]") && input.includes("println(data[0])"),
      correct_output: "0", error_tip: "Initialization uses `new int[size]` syntax. Array elements are 0-indexed.",
      hint: "The declaration is `int[] data = new int[4];`", expected_code: "int[] data = new int[4];\nSystem.out.println(data[0]);" },
    { id: 67, title: "Assigning Array Elements", prompt: "Given `String[] names = new String[3];`. Assign the value \"Alice\" to the element at index 2. Print the element.",
      validation: (input) => input.includes("String[] names = new String[3]") && input.includes("names[2] = \"Alice\"") && input.includes("println(names[2])"),
      correct_output: "Alice", error_tip: "Use `arrayName[index] = value;` to assign.",
      hint: "Index 2 refers to the third slot.", expected_code: "String[] names = new String[3];\nnames[2] = \"Alice\";\nSystem.out.println(names[2]);" },
    { id: 68, title: "Array Literal Initialization", prompt: "Declare a boolean array `flags` containing the values true, false, true, using the shorthand literal syntax.",
      validation: (input) => input.includes("boolean[] flags = {true, false, true}") && input.includes(";"),
      correct_output: "(Array declared successfully)", error_tip: "Use curly braces `{}` with comma-separated values for the shorthand.",
      hint: "The shorthand declaration is: `boolean[] flags = { true, false, true };`", expected_code: "boolean[] flags = {true, false, true};" },
    { id: 69, title: "Looping and Calculating Array Sum", prompt: "Given `int[] nums = {10, 20, 30};`. Use an enhanced `for` loop to calculate and print the sum of all elements.",
      validation: (input) => input.includes("int[] nums") && input.includes("int total = 0") && input.includes("for (int num : nums)") && input.includes("total += num") && input.includes("println(total)"),
      correct_output: "60", error_tip: "Total must be initialized to 0. Use `total += num;` inside the loop.",
      hint: "Use the enhanced loop: `for (int num : nums)`.", expected_code: "int[] nums = {10, 20, 30};\nint total = 0;\nfor (int num : nums) {\ntotal += num;\n}\nSystem.out.println(total);" },
    { id: 70, title: "Finding Array Maximum", prompt: "Given `int[] temps = {22, 28, 15};`. Find and print the highest temperature (28) using a loop.",
      validation: (input) => input.includes("int[] temps") && input.includes("int max = temps[0]") && input.includes("for") && input.includes("if (temp > max)") && input.includes("max = temp"),
      correct_output: "28", error_tip: "Start by setting `max` to the first element and iterate through the rest.",
      hint: "Initialize `int max = temps[0];`. Use an enhanced loop and an `if` condition to update `max`.", expected_code: "int[] temps = {22, 28, 15};\nint max = temps[0];\nfor (int temp : temps) {\nif (temp > max) {\nmax = temp;\n}\n}\nSystem.out.println(max);" },
    { id: 71, title: "Multidimensional Array (Declaration)", prompt: "Declare a 2D integer array named `matrix` initialized to hold 3 rows and 2 columns.",
      validation: (input) => input.includes("int[][] matrix = new int[3][2]") && input.includes(";"),
      correct_output: "(2D Array declared successfully)", error_tip: "2D arrays require two sets of square brackets `[][]` and two sizes.",
      hint: "Use `int[][] matrix = new int[3][2];`", expected_code: "int[][] matrix = new int[3][2];" },
    { id: 72, title: "Multidimensional Array (Access)", prompt: "Given `int[][] grid = {{1, 2}, {3, 4}};`. Print the value at the second row, first column (value 3).",
      validation: (input) => input.includes("int[][] grid") && input.includes("grid[1][0]") && input.includes("println"),
      correct_output: "3", error_tip: "Remember indices start at 0. Second row is index 1; first column is index 0.",
      hint: "The index to access 3 is `[1][0]`.", expected_code: "int[][] grid = {{1, 2}, {3, 4}};\nSystem.out.println(grid[1][0]);" },
    { id: 73, title: "Array of Strings Literal", prompt: "Declare a String array `names` containing \"Fred\" and \"George\". Print the size/length of the array.",
      validation: (input) => input.includes("String[] names") && input.includes("\"Fred\", \"George\"") && input.includes("names.length") && input.includes("println"),
      correct_output: "2", error_tip: "Use `.length` to get the array size.",
      hint: "Use `names.length` inside println().", expected_code: "String[] names = {\"Fred\", \"George\"};\nSystem.out.println(names.length);" },
    { id: 74, title: "Modifying Array Element", prompt: "Given `int[] data = {10, 20, 30};`. Change the value at index 0 to 5. Print the new value at index 0.",
      validation: (input) => input.includes("int[] data") && input.includes("data[0] = 5") && input.includes("println(data[0])"),
      correct_output: "5", error_tip: "Use the assignment operator (`=`) to change the element value.",
      hint: "The assignment is: `data[0] = 5;`", expected_code: "int[] data = {10, 20, 30};\ndata[0] = 5;\nSystem.out.println(data[0]);" },
    { id: 75, title: "Looping 2D Array", prompt: "Given `int[][] matrix = {{1, 0}, {0, 1}};`. Use nested loops to print every element.",
      validation: (input) => input.includes("int[][] matrix") && input.includes("for (int[] row : matrix)") && input.includes("for (int val : row)") && input.includes("println(val)"),
      correct_output: "1\n0\n0\n1", error_tip: "Use an outer enhanced loop for rows, and an inner enhanced loop for columns/values.",
      hint: "Outer loop: `for (int[] row : matrix)`. Inner loop: `for (int val : row)`.", expected_code: "int[][] matrix = {{1, 0}, {0, 1}};\nfor (int[] row : matrix) {\nfor (int val : row) {\nSystem.out.println(val);\n}\n}" },

    // --- SECTION 7: METHODS (76-90) ---
    { id: 76, title: "Method Definition (Void, No Params)", prompt: "Create a **public static void** method named `launch` that accepts no arguments. Inside, print <span class='highlight'>Rocket Launched!</span>",
      validation: (input) => input.includes("public static void launch()") && input.includes("\"Rocket Launched!\""),
      correct_output: "(Method definition saved)", error_tip: "The required signature is `public static void launch()`.",
      hint: "The structure is `public static void launch() { ... }`", expected_code: "public static void launch() {\nSystem.out.println(\"Rocket Launched!\");\n}" },
    { id: 77, title: "Method Invocation (Calling)", prompt: "Assume a `public static void start()` method exists. Write the line of code to call this method.",
      validation: (input) => input.includes("start()") && input.includes(";"),
      correct_output: "(Method called)", error_tip: "Method invocation requires the method name followed by parentheses and a semicolon.",
      hint: "It's just `start();`", expected_code: "start();" },
    { id: 78, title: "Method with Parameters (Void)", prompt: "Create a **public static void** method `sayName` accepting one String parameter `name`. Print \"Hello, \" + `name` inside.",
      validation: (input) => input.includes("public static void sayName(String name)") && input.includes("\"Hello, \" + name"),
      correct_output: "(Method definition saved)", error_tip: "The signature is `public static void sayName(String name)`.",
      hint: "The print statement should use concatenation: `\"Hello, \" + name`.", expected_code: "public static void sayName(String name) {\nSystem.out.println(\"Hello, \" + name);\n}" },
    { id: 79, title: "Method with Return (Int)", prompt: "Create a **public static** method named `getTen` that returns the integer value 10.",
      validation: (input) => input.includes("public static int getTen()") && input.includes("return 10") && input.includes(";"),
      correct_output: "(Method definition saved)", error_tip: "The return type must be `int` and you must use the `return` keyword.",
      hint: "The signature is `public static int getTen()`.", expected_code: "public static int getTen() {\nreturn 10;\n}" },
    { id: 80, title: "Method with Return (Double)", prompt: "Create a **public static** method named `getTaxRate` that returns the double value 0.05.",
      validation: (input) => input.includes("public static double getTaxRate()") && input.includes("return 0.05") && input.includes(";"),
      correct_output: "(Method definition saved)", error_tip: "The return type must be `double`.",
      hint: "The signature is `public static double getTaxRate()`.", expected_code: "public static double getTaxRate() {\nreturn 0.05;\n}" },
    { id: 81, title: "Method Return & Invocation", prompt: "Assume `public static int add(int a, int b)` exists. Call this method with values 5 and 3, store the result in `sum`, and print `sum`.",
      validation: (input) => input.includes("int sum") && input.includes("add(5, 3)") && input.includes("println(sum)"),
      correct_output: "8", error_tip: "You must declare the variable `sum` and assign the method call to it.",
      hint: "The method call is `sum = add(5, 3);`", expected_code: "int sum = add(5, 3);\nSystem.out.println(sum);" },
    { id: 82, title: "Return from Method (Calculation)", prompt: "Create a **public static int** method `multiply(int x, int y)` that returns the product of `x` and `y`.",
      validation: (input) => input.includes("public static int multiply(int x, int y)") && input.includes("return x * y") && input.includes(";"),
      correct_output: "(Method definition saved)", error_tip: "The return statement should be `return x * y;`.",
      hint: "The method returns an integer, so the signature must use `int`.", expected_code: "public static int multiply(int x, int y) {\nreturn x * y;\n}" },
    { id: 83, title: "Overloading Methods (1)", prompt: "Create a **public static int** method named `count(int x)` that returns `x + 1`.",
      validation: (input) => input.includes("public static int count(int x)") && input.includes("return x + 1") && input.includes(";"),
      correct_output: "(Method definition saved)", error_tip: "Ensure the parameter is `int x`.",
      hint: "This is a simple method definition.", expected_code: "public static int count(int x) {\nreturn x + 1;\n}" },
    { id: 84, title: "Overloading Methods (2)", prompt: "Create a second **public static int** method named `count(int x, int y)` that returns `x + y`.",
      validation: (input) => input.includes("public static int count(int x, int y)") && input.includes("return x + y") && input.includes(";"),
      correct_output: "(Method definition saved)", error_tip: "Method overloading means having the same name but different parameters.",
      hint: "This method requires two parameters.", expected_code: "public static int count(int x, int y) {\nreturn x + y;\n}" },
    { id: 85, title: "Passing by Value", prompt: "Given `int start = 10;`. Create a method call to `modify(start)` where `modify` is defined as `public static void modify(int val) { val = 0; }`. Print `start`.",
      validation: (input) => input.includes("int start = 10") && input.includes("modify(start)") && input.includes("println(start)"),
      correct_output: "10", error_tip: "Java passes primitives (like int) by value, so the original variable `start` is unaffected.",
      hint: "The output should be the original value of `start`.", expected_code: "int start = 10;\nmodify(start);\nSystem.out.println(start);\npublic static void modify(int val) { val = 0; }" },

    // --- SECTION 8: CLASSES & OBJECTS (91-100) ---
    { id: 86, title: "Class Definition", prompt: "Define an empty public class named <span class='highlight'>GameServer</span>.",
      validation: (input) => input.includes("public class GameServer {") && input.includes("}"),
      correct_output: "(Class definition saved)", error_tip: "Use the `public class ClassName { ... }` structure.",
      hint: "The structure is `public class GameServer { }`", expected_code: "public class GameServer { }" },
    { id: 87, title: "Object Instantiation", prompt: "Assume class `Player` exists. Create a new object of type `Player` named `p1`.",
      validation: (input) => input.includes("Player p1") && input.includes("new Player()") && input.includes(";"),
      correct_output: "(Object p1 created)", error_tip: "Use the `new` keyword and the constructor `Player()`.",
      hint: "The syntax is: `Player p1 = new Player();`", expected_code: "Player p1 = new Player();" },
    { id: 88, title: "Adding a Field (Member Variable)", prompt: "Inside the provided `class User {}`, add a public integer field named `level` initialized to 1.",
      validation: (input) => input.includes("public class User {") && input.includes("public int level = 1") && input.includes(";"),
      correct_output: "(Field added)", error_tip: "Fields are defined inside the class body, using the visibility keyword.",
      hint: "The definition is: `public int level = 1;`", expected_code: "public class User {\npublic int level = 1;\n}" },
    { id: 89, title: "Accessing Object Fields", prompt: "Given `class Player { public int health = 100; }` and `Player p = new Player();`. Print the `health` field of object `p`.",
      validation: (input) => input.includes("Player p = new Player()") && input.includes("println(p.health)"),
      correct_output: "100", error_tip: "Use the dot operator (`.`) to access fields: `object.fieldName`.",
      hint: "The print statement is: `System.out.println(p.health);`", expected_code: "class Player { public int health = 100; }\nPlayer p = new Player();\nSystem.out.println(p.health);" },
    { id: 90, title: "Calling Object Methods", prompt: "Given `class Item { public void inspect() { System.out.println(\"Inspecting\"); } }` and `Item sword = new Item();`. Call the `inspect` method.",
      validation: (input) => input.includes("Item sword = new Item()") && input.includes("sword.inspect()") && input.includes(";"),
      correct_output: "Inspecting", error_tip: "Use the dot operator to call methods: `object.methodName();`.",
      hint: "The method call is `sword.inspect();`", expected_code: "class Item { public void inspect() { System.out.println(\"Inspecting\"); } }\nItem sword = new Item();\nsword.inspect();" },
    { id: 91, title: "Adding a Constructor (No Params)", prompt: "Inside the provided `class User {}`, add a public constructor that prints <span class='highlight'>New User Created</span>.",
      validation: (input) => input.includes("public User()") && input.includes("\"New User Created\""),
      correct_output: "(Constructor added)", error_tip: "The constructor name must match the class name, and it has no return type.",
      hint: "The definition is: `public User() { System.out.println(\"New User Created\"); }`", expected_code: "public class User {\npublic User() {\nSystem.out.println(\"New User Created\");\n}\n}" },
    { id: 92, title: "Constructor Invocation", prompt: "Assume `class Log { public Log(String msg) { System.out.println(msg); } }`. Create a new `Log` object, passing \"Starting up...\" as the argument.",
      validation: (input) => input.includes("new Log(\"Starting up...\")") && input.includes(";"),
      correct_output: "Starting up...", error_tip: "The argument must be passed inside the parentheses of the `new` keyword.",
      hint: "The syntax is: `new Log(\"Starting up...\");`", expected_code: "class Log { public Log(String msg) { System.out.println(msg); } }\nnew Log(\"Starting up...\");" },
    { id: 93, title: "The `this` Keyword", prompt: "Given `class Item { private String name; public Item(String name) { ... } }`. Inside the constructor body, use `this` to assign the parameter `name` to the field `name`.",
      validation: (input) => input.includes("this.name = name") && input.includes(";"),
      correct_output: "(Assignment successful)", error_tip: "Use `this.fieldName = parameterName;` to disambiguate.",
      hint: "The line is: `this.name = name;`", expected_code: "class Item { private String name; public Item(String name) {\nthis.name = name;\n} }" },
    { id: 94, title: "Private Fields", prompt: "Inside the provided `class Entity {}`, add a private integer field named `id`.",
      validation: (input) => input.includes("private int id") && input.includes(";"),
      correct_output: "(Private field added)", error_tip: "Use the `private` access modifier.",
      hint: "The definition is: `private int id;`", expected_code: "public class Entity {\nprivate int id;\n}" },
    { id: 95, title: "Getter Method", prompt: "Given `class Data { private int value = 5; }`. Create a **public int** getter method named `getValue` that returns the field `value`.",
      validation: (input) => input.includes("public int getValue()") && input.includes("return value") && input.includes(";"),
      correct_output: "(Getter method added)", error_tip: "The return type must match the field type (`int`).",
      hint: "The method body is simply `return value;`", expected_code: "class Data { private int value = 5; }\npublic int getValue() {\nreturn value;\n}" },
    
    // --- SCALABILITY FILLERS (96-100) ---
    { id: 96, title: "Setter Method", prompt: "Given `class Data { private String key; }`. Create a **public void** setter method named `setKey` that accepts a String parameter `newKey` and assigns it to `key`.",
      validation: (input) => input.includes("public void setKey(String newKey)") && input.includes("key = newKey") && input.includes(";"),
      correct_output: "(Setter method added)", error_tip: "Setter methods are typically `void`.",
      hint: "The method body is `key = newKey;`", expected_code: "class Data { private String key; }\npublic void setKey(String newKey) {\nkey = newKey;\n}" },
    { id: 97, title: "Static Field (1)", prompt: "Inside `class Config {}`, add a public static final String field named `DEFAULT_ENV` initialized to \"prod\".",
      validation: (input) => input.includes("public static final String DEFAULT_ENV") && input.includes("\"prod\"") && input.includes(";"),
      correct_output: "(Static field added)", error_tip: "Use `public static final` keywords.",
      hint: "The definition is: `public static final String DEFAULT_ENV = \"prod\";`", expected_code: "public class Config {\npublic static final String DEFAULT_ENV = \"prod\";\n}" },
    { id: 98, title: "Static Field (2) Access", prompt: "Assume `Config.DEFAULT_ENV` exists and equals \"prod\". Print the value of `Config.DEFAULT_ENV`.",
      validation: (input) => input.includes("println(Config.DEFAULT_ENV)"),
      correct_output: "prod", error_tip: "Static fields are accessed directly via the Class name, not an object.",
      hint: "Use `Config.DEFAULT_ENV` inside println().", expected_code: "System.out.println(Config.DEFAULT_ENV);" },
    { id: 99, title: "Main Method Call", prompt: "Assume you have a method `startEngine()` in a utility class `Utils`. Call this static method.",
      validation: (input) => input.includes("Utils.startEngine()") && input.includes(";"),
      correct_output: "(Static method called)", error_tip: "Static methods are called using the Class name: `ClassName.methodName();`",
      hint: "The call is `Utils.startEngine();`", expected_code: "Utils.startEngine();" },
    { id: 100, title: "Final Review", prompt: "Print your name, <span class='highlight'>Elias Saire</span>, and a happy message to complete the course!",
      validation: (input) => input.includes("System.out.println") && input.includes("\"Elias Saire\"") && input.includes(";"),
      correct_output: "Elias Saire", error_tip: "This is a simple print statement review.",
      hint: "Go back to Lesson 1!", expected_code: "System.out.println(\"Elias Saire\");" }
];